### ISSUE TITLE
上传出错

### ISSUE THREAD

**Issue by 1753449579** [renmu123/biliLive-tools#9]
[2024-02-05 21:47:47.242] [error] task rqhbuqu3ucc error: Error: 合并视频失败
[2024-02-05 21:47:47.244] [error] task rqhbuqu3ucc error: 上传中止
[2024-02-05 21:47:47.245] [error] undefined
[2024-02-05 21:47:47.245] [error] unhandledRejection Error: 上传中止
    at PQueue.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\biliLive-tools\resources\app.asar\node_modules\@renmu\bili-api\dist\index.cjs:19173:23)
    at PQueue.emit (C:\Users\Administrator\AppData\Local\Programs\biliLive-tools\resources\app.asar\node_modules\@renmu\bili-api\dist\index.cjs:18122:36)
    at #tryToStartAnother (C:\Users\Administrator\AppData\Local\Programs\biliLive-tools\resources\app.asar\node_modules\@renmu\bili-api\dist\index.cjs:18552:22)
    at #next (C:\Users\Administrator\AppData\Local\Programs\biliLive-tools\resources\app.asar\node_modules\@renmu\bili-api\dist\index.cjs:18513:32)
    at C:\Users\Administrator\AppData\Local\Programs\biliLive-tools\resources\app.asar\node_modules\@renmu\bili-api\dist\index.cjs:18646:31
[2024-02-05 21:47:47.246] [error] unhandledRejection Error: 合并视频失败
    at WebVideoUploader.upload (C:\Users\Administrator\AppData\Local\Programs\biliLive-tools\resources\app.asar\node_modules\@renmu\bili-api\dist\index.cjs:18966:19)
    at async C:\Users\Administrator\AppData\Local\Programs\biliLive-tools\resources\app.asar\node_modules\@renmu\bili-api\dist\index.cjs:18633:36

**Comment by renmu123** [comment]
这个报错出现的频率怎么样，可能是由于网络原因导致最后的合并切片失败，~~也有可能是b站抽风了~~，你可以尝试单独上传该视频看看还是否会报错

**Comment by 1753449579** [comment]
文件太大会报错，一下子上传了17G，用biliup解决了
